version: '3'
services:
  mysql:
    container_name: database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wandelBankjePass@123
      MYSQL_DATABASE: wandelbankje_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db: