version: "3"
services:
  wandelserver:
    image: ghcr.io/siebsie23/wandelbankje-server:latest
    restart: unless-stopped
    networks:
      - backend
  wandeladmin:
    image: ghcr.io/siebsie23/wandelbankje-admin:latest
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - .:/var/www/html
  mysql:
    container_name: database
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wandelBankjePass@123
      MYSQL_DATABASE: wandelbankje_db
    ports:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    driver: bridge