version: "3"
services:
  wandelserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
  mysql:
    container_name: database
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wandelBankjePass@123
      MYSQL_DATABASE: wandelbankje_db
    ports:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    driver: bridge